apiVersion: v1
kind: Service
metadata:
  name: {{ include "c-web-socket-server.fullname" . }}
  labels:
    {{- include "c-web-socket-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "c-web-socket-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: tcp-chat
      port: {{ .Values.service.port }}
      targetPort: tcp-chat
      protocol: TCP
