replicaCount: 1

image:
  repository: ghcr.io/pedrovmota/c-web-socket-server
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5555

env:
  CHAT_HOST: "0.0.0.0"
  CHAT_PORT: "5555"
  CHAT_MAX_CLIENTS: "64"
  CHAT_BACKLOG: "16"
  CHAT_BUFFER_SIZE: "4096"

resources: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 100
  runAsGroup: 101
  fsGroup: 101

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
