apiVersion: v1
kind: ConfigMap
metadata:
  name: c-web-socket-server-config
  labels:
    app.kubernetes.io/name: c-web-socket-server
    app.kubernetes.io/part-of: iot-p3
data:
  CHAT_HOST: "0.0.0.0"
  CHAT_PORT: "5555"
  CHAT_MAX_CLIENTS: "64"
  CHAT_BACKLOG: "16"
  CHAT_BUFFER_SIZE: "4096"
